// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data.ts
var services = [
  {
    slug: "uk-visit-visa",
    name: "UK Visit Visa",
    category: "visa",
    path: "/uk-visa",
    summary: "End-to-end assistance for UK standard visitor visas: document checklist, financial evidence review, cover letter drafting, application submission and appointment booking.",
    highlights: [
      "Eligibility assessment and refusal-risk review",
      "Document checklist and sponsorship letters",
      "Online application form completion and biometrics appointment"
    ]
  },
  {
    slug: "student-visa",
    name: "Student Visa",
    category: "visa",
    path: "/student-visa",
    summary: "Study abroad guidance covering university shortlisting, admission applications, CAS/I-20 support and student visa filing for the UK, USA, Canada, Australia and Europe.",
    highlights: [
      "University and course selection",
      "Admission and scholarship applications",
      "Financial documentation and visa interview preparation"
    ]
  },
  {
    slug: "other-country-visas",
    name: "Other Country Visas",
    category: "visa",
    path: "/visa-services",
    summary: "Worldwide visa processing for tourist, business and family visit categories across Schengen, USA, Canada, Australia, Middle East and Asian destinations.",
    highlights: [
      "Schengen, USA, Canada, Australia and UAE visas",
      "Business and family visit applications",
      "Appointment booking and document attestation"
    ]
  },
  {
    slug: "hajj-umrah",
    name: "Hajj & Umrah",
    category: "visa",
    path: "/hajj-umrah",
    summary: "Sacred journey packages with visa processing, flights, Makkah and Madinah accommodation, ground transport and guided religious support.",
    highlights: [
      "Hajj and Umrah visa processing",
      "Hotels close to the Haram",
      "Guided groups and transport between holy sites"
    ]
  },
  {
    slug: "summer-schools",
    name: "Summer Schools",
    category: "program",
    path: "/summer-schools",
    summary: "ESL and academic summer programs in the UK and USA for young learners and teenagers, including accommodation, activities and airport transfers.",
    highlights: [
      "English language and academic enrichment courses",
      "Residential and homestay accommodation",
      "Excursions and supervised activity programs"
    ]
  },
  {
    slug: "travel-packages",
    name: "Travel Packages",
    category: "program",
    path: "/travel-packages",
    summary: "Curated worldwide holiday packages: honeymoons, family holidays, group tours and bespoke luxury itineraries built around your dates and budget.",
    highlights: [
      "Bespoke itineraries with flights and hotels",
      "Honeymoon, family and group travel",
      "24/7 support while you travel"
    ]
  }
];
var companyInfo = {
  name: "Notting Hill Voyages",
  tagline: "Luxury travel experiences, visa services and study abroad guidance.",
  phone: "+44 7385 608 114",
  email: "info@nottinghillvoyages.com",
  location: "Sylhet, Bangladesh",
  consultationUrl: "https://calendly.com/nottinghillvoyages"
};

// src/lib/mcp/tools/list-services.ts
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List the visa services and travel programs offered by Notting Hill Voyages, optionally filtered by category.",
  inputSchema: {
    category: z.enum(["visa", "program"]).optional().describe("Filter by 'visa' services or travel/study 'program' offerings.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? services.filter((s) => s.category === category) : services;
    return {
      content: [
        {
          type: "text",
          text: items.map((s) => `${s.name} (${s.slug}): ${s.summary}`).join("\n\n")
        }
      ],
      structuredContent: { services: items }
    };
  }
});

// src/lib/mcp/tools/get-service.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_service_default = defineTool2({
  name: "get_service",
  title: "Get service details",
  description: "Get full details for one Notting Hill Voyages service or program by its slug (see list_services).",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Service slug, e.g. 'uk-visit-visa'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const service = services.find((s) => s.slug === slug.toLowerCase());
    if (!service) {
      throw new ToolError(
        `No service found with slug "${slug}". Available: ${services.map((s) => s.slug).join(", ")}`
      );
    }
    return {
      content: [
        {
          type: "text",
          text: `${service.name}
${service.summary}

Highlights:
- ${service.highlights.join("\n- ")}
Page: ${service.path}`
        }
      ],
      structuredContent: { service }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Get Notting Hill Voyages contact details and the consultation booking link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `${companyInfo.name} \u2014 ${companyInfo.tagline}
Phone: ${companyInfo.phone}
Email: ${companyInfo.email}
Location: ${companyInfo.location}
Book a consultation: ${companyInfo.consultationUrl}`
      }
    ],
    structuredContent: { company: companyInfo }
  })
});

// src/lib/mcp/tools/submit-inquiry.ts
import { defineTool as defineTool4, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function firstEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function publishableKey() {
  const direct = firstEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        );
        if (key) return key.trim();
      }
    } catch {
    }
  }
  return firstEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
}
var submit_inquiry_default = defineTool4({
  name: "submit_inquiry",
  title: "Submit travel inquiry",
  description: "Send a travel, visa or study-abroad inquiry to the Notting Hill Voyages team. The team replies by email within 24 hours.",
  inputSchema: {
    name: z3.string().trim().min(1).describe("Full name of the person inquiring."),
    email: z3.string().trim().email().describe("Email address for the reply."),
    phone: z3.string().trim().optional().describe("Contact phone number, optional."),
    destination: z3.string().trim().optional().describe("Destination or service of interest, e.g. 'UK visit visa'."),
    message: z3.string().trim().min(1).describe("Details of the inquiry.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input) => {
    const url = firstEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
    const key = publishableKey();
    if (!url || !key) throw new ToolError2("Inquiry service is not configured.");
    const response = await fetch(`${url}/functions/v1/send-inquiry`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: key,
        Authorization: `Bearer ${key}`
      },
      body: JSON.stringify(input)
    });
    if (!response.ok) {
      throw new ToolError2(`Could not send the inquiry (status ${response.status}).`);
    }
    return {
      content: [
        {
          type: "text",
          text: `Inquiry sent for ${input.name}. A confirmation email was sent to ${input.email} and the team will reply within 24 hours.`
        }
      ],
      structuredContent: { submitted: true }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "notting-hill-voyages",
  title: "Notting Hill Voyages",
  version: "0.1.0",
  instructions: "Tools for Notting Hill Voyages, a luxury travel, visa and study-abroad agency. Use `list_services` and `get_service` to answer questions about visa and travel offerings, `get_contact_info` for contact and booking details, and `submit_inquiry` to send a customer inquiry to the team.",
  tools: [list_services_default, get_service_default, get_contact_info_default, submit_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
